name: Deriv Deploy storybook

on:
    push:
        branches:
            - test_storybook_deployment
        paths:
            - 'packages/components/stories/**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install and Build ğŸ”§
              run: |
                  npm run bootstrap
                  cd ./packages/components
                  npm run storybook:build

            - name: Deploy ğŸš€
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: packages/components/.out
                  CLEAN: true
